version: '3.8'

services:
  web:
    build: .
    # NOVO COMANDO: Apenas inicia o contêiner com um shell para depuração.
    command: bash
    ports:
      - "3000"
    volumes:
      - .:/rails
      - bundle_data:/usr/local/bundle
      - sqlite_data:/rails/storage
    environment:
      RAILS_ENV: development
      DATABASE_URL: sqlite3:///rails/storage/development.sqlite3

volumes:
  sqlite_data:
  bundle_data: