# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  # For local development/test, keep these:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: your_app_development # Replace with your actual local dev DB name

test:
  <<: *default
  database: your_app_test # Replace with your actual local test DB name

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # All other database connection details (host, port, username, password, db name)
  # will be parsed automatically from the DATABASE_URL environment variable
  # provided by Elastic Beanstalk for the associated RDS instance.
