# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: working_hotwire_app_development
  # username: your_dev_username # Optional: if you have a local PostgreSQL user
  # password: your_dev_password # Optional: if you have a local PostgreSQL password

test:
  <<: *default
  database: working_hotwire_app_test

production:
  <<: *default
  database: <%= ENV['RAILS_DB_NAME'] %>
  username: <%= ENV['RAILS_DB_USERNAME'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %>
  host: <%= ENV['RAILS_DB_HOST'] %>
  port: <%= ENV['RAILS_DB_PORT'] %>
  url: <%= ENV['DATABASE_URL'] %> # Render will provide this automatically
